#druid数据源配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: wuxian6636928
      driver-class-name: com.mysql.cj.jdbc.Driver
      web-stat-filter:
        enabled: true
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true